name: 'Pull Request Labeler'

on:
  - pull_request_target

jobs:
  labeler:
    name: 'Labelling Pull Requests'

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: 'Define labels'
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
